### ISSUE TITLE
reposync过程中报错，如何搞

### ISSUE THREAD

**Issue by ryan016** [sdogsq/JDActions#2]
2s
Run repo-sync/github-sync@v2
  with:
    source_repo: https://github.com/an0na/DontForkXieXie.git
    source_branch: master
    destination_branch: main
    github_token: ***
  env:
    PAT: ***
/usr/bin/docker run --name ghcrioreposyncgithubsyncv230_ebaba3 --label 2f1ee0 --workdir /github/workspace --rm -e PAT -e INPUT_SOURCE_REPO -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_BRANCH -e INPUT_GITHUB_TOKEN -e INPUT_SYNC_TAGS -e GITHUB_TOKEN -e SYNC_TAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/JD-qiandao/JD-qiandao":"/github/workspace" ghcr.io/repo-sync/github-sync:v2.3.0  "https://github.com/an0na/DontForkXieXie.git" "master:main"

**Comment by thesound666** [comment]
同问

**Comment by sdogsq** [comment]
最近我在手动更新，已经把reposync改为自动同步本仓库
