### ISSUE TITLE
中午时分开始脚本全面失效了

### ISSUE THREAD

**Issue by ryan016** [sdogsq/JDActions#3]
不知还能自动同步更新否

**Comment by sdogsq** [comment]
我检查了一下，所有的github action 中午之后都出现了问题，包括但不限于本repo，所以应该是github服务器出现了问题。

**Comment by ryan016** [comment]
收到！！谢谢！！

**Comment by sdogsq** [comment]
已经修复了，原来使用的script repo也被删除了，现在用的是@shuye72 的scripts，推荐直接使用他的action repo，我最近比较忙，先给本repo打个补丁，周末看有空来专门整理一下。
